# Used for content/masthead
development:
  dashboard_base_url: "http://www.local.malmo.se:3000/"
  sv_base_url: "https://komin.malmo.se/"
  site_search_url: "http://www.local.malmo.se:3000/search"

test: &test
  dashboard_base_url: "https://minsidatest.malmo.se/"
  sv_base_url: "https://komin.test.malmo.se/"
  site_search_url: "//kominsok.malmo.se"

staging:
  <<: *test

production:
  dashboard_base_url: "https://minsida.malmo.se/"
  sv_base_url: "https://komin.malmo.se/"
  site_search_url: "//kominsok.malmo.se"
