# Used for content/masthead
development:
  dashboard_base_url: "http://www.local.malmo.se:3000/"
  sv_base_url: "https://komin.malmo.se/"
  site_search_url: "http://www.local.malmo.se:3000/search"

test: &test
  dashboard_base_url: "https://webapps06.malmo.se/dashboard-test/"
  sv_base_url: "https://komin.test.malmo.se/"
  site_search_url: "//s2.malmo.se"

staging:
  <<: *test

production:
  dashboard_base_url: "https://webapps06.malmo.se/dashboard/"
  sv_base_url: "https://komin.malmo.se/"
  site_search_url: "//s2.malmo.se"
