# Used for content/masthead
development: &development
  sv_base_url: "http://www.test.malmo.se/"
  site_search_ac_url: "http://malmo.appliance.siteseeker.se/qc/webb/qc"

test: &test
  <<: *development
staging:
  <<: *test

production:
  <<: *development
  sv_base_url: "https://www.malmo.se/"
