# Used for content/masthead
development: &development
  sv_base_url: "/"
  site_search_ac_url: "http://malmo.appliance.siteseeker.se/qc/webb/qc"
  site_search_url: http://s1.malmo.se/

test: &test
  <<: *development
staging:
  <<: *test

production:
  <<: *development
  sv_base_url: "/juni2014/"
