# Used for content/masthead
default: &default
  sv_base_url: http://www.test.malmo.se
  site_search_url: http://s1.malmo.se/
  site_search_ac_url: http://s1.malmo.se/search/autocomplete

development: &development
  <<: *default
  site_search_url: http://www.local.malmo.se:3000
  site_search_ac_url: http://www.local.malmo.se:3000/search/autocomplete

test:
  <<: *default
  site_search_ac_url: http://www.local.malmo.se:3000/search/autocomplete

production: &staging
  <<: *default
  sv_base_url: https://www.malmo.se/

staging:
  <<: *default
  site_search_url: http://188.226.179.132/
  site_search_ac_url: http://188.226.179.132/search/autocomplete
